project:
  type: website
  output-dir: docs

website:
  title: "Solveig Senf"
  navbar:
    left: #tabs
      - href: index.qmd
        text: Home
      - about_me.qmd
      - href: mini_project_one.qmd
        text: Mini Project 1
      - href: mini_project_two.qmd
        text: Mini Project 2
      - href: mini_project_four.qmd
        text: Mini Project 4
      - href: tip_of_the_day.qmd
        text: R Tip of the Day

format:
  html:
    theme: cosmo #nice clean theme
    mainfont: "Times New Roman" 
    toc: true

editor: visual

